apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  namespace : monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30009

